version: '3'

services:
  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: ledgerappuserdata
    command:
      /app/cmd/ledger/main

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledgerappuserdata

  nginx:
    image: nginx:latest
    container_name: ledgerapp_nginx
    build: ./deployer/nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app